repos:
  - repo: local
    hooks:
      - id: opa-fmt
        name: OPA fmt
        description: Formats Rego policy using opa fmt
        entry: opa fmt
        args: [ -w ]
        language: system
        files: (\.rego)$

#      - id: opa-bundle
#        name: OPA bundle
#        description: Formats Rego policy using opa fmt
#        entry: opa build
#        args: [ -b, '.',  -e, './compliance' ]
#        language: system
#        files: (\.rego)$

      - id: opa-check
        name: OPA check
        description: Check syntax of staged Rego files
        entry: opa check
        args: [ -S, './compliance' ]
        pass_filenames: false
        language: system
        files: (\.rego)$

      - id: opa-test
        name: OPA test
        description: Runs OPA unit tests on rego source files
        entry: opa test
        args: [ -b, '.' ]
        pass_filenames: false
        language: system