repos:
  - repo: local
    hooks:
      - id: opa-fmt
        name: OPA fmt
        description: Formats Rego policy using opa fmt
        entry: opa fmt
        args: [ -w ]
        language: system
        files: (\.rego)$

      - id: opa-check
        name: OPA check
        description: Check syntax of staged Rego files
        entry: opa check
        args: [ -S, './bundle/compliance' ]
        pass_filenames: false
        language: system
        files: (\.rego)$

      - id: opa-test
        name: OPA test
        description: Runs OPA unit tests on rego source files
        entry: opa test
        args: [ -b, './bundle' ]
        pass_filenames: false
        language: system

      - id: update-rules-status
        name: Update rules status
        description: Update rules status in rules_table.md
        entry: poetry run python ./dev/update_rule_status.py
        language: system

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
      - id: markdownlint
        args: [ '--disable',
                MD013,  # Line length can be ignored for now
                MD033,  # Allow inline HTML
                MD046,  # Allow code blocks to be fenced with backticks
                MD041,  # Allow multiple top level headers
                '--' ]
        files: \.(md|markdown)$