name: Test Policies

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test-rego-policies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: OPA build
        uses: docker://openpolicyagent/opa
        with:
          args: "build -b . -e ./compliance"
      - name: OPA test
        uses: docker://openpolicyagent/opa
        with:
          args: "test -b . -v"
      - name: OPA check -strict
        uses: docker://openpolicyagent/opa
        with:
          args: "check --strict --bundle ."
