name: Test Policies

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test-rego-policies:
    name: Test Rego Policies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: 0.53.1

      - name: OPA format
        run: opa fmt ./bundle --fail=true --diff

      - name: OPA format list failed files
        run: opa fmt ./bundle --list

      - name: OPA build
        run: opa build -b ./bundle -e ./bundle/compliance

      - name: OPA test
        run: opa test -b ./bundle -v

      - name: OPA check -strict
        run: opa check --strict --bundle ./bundle

      - name: Set up Regal
        uses: StyraInc/setup-regal@v0.1.0
        with:
          version: v0.10.1

      - name: Lint Rego
        run: regal lint --format github bundle

  update-rules-status:
    name: Update rules status
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Update rules status
        run: poetry run python ./dev/update_rule_status.py

      - name: File Rules.md is not updated - to fix run our pre-commit hooks
        run: git diff --exit-code

  update-rule-metadata:
    name: Update rules metadata
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Update rule metadata
        run: poetry run python ./dev/generate_rule_metadata.py

      - name: Rule metadata mismatch - to fix run our pre-commit hooks
        run: git diff --exit-code
