name: Test Policies

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test-rego-policies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: OPA format
        uses: docker://openpolicyagent/opa:0.45.0
        with:
          args: "fmt ./bundle --fail=true --diff"

      - name: OPA format list failed files
        uses: docker://openpolicyagent/opa
        if: always()
        with:
          args: "fmt ./bundle --list"

      - name: OPA build
        uses: docker://openpolicyagent/opa
        with:
          args: "build -b ./bundle -e ./bundle/compliance"

      - name: OPA test
        uses: docker://openpolicyagent/opa
        with:
          args: "test -b ./bundle -v"

      - name: OPA check -strict
        uses: docker://openpolicyagent/opa
        with:
          args: "check --strict --bundle ./bundle"

  update-rules-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
          uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

        - name: Update rules status
          run: |
            python3 ./dev/update_rule_status.py
