name: Code Coverage Badge

on:
  pull_request:
  push:
    branches: [main]


jobs:
  test-rego-policies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Run opa test
        uses: b4b4r07/action-opa@master
        with:
          path: compliance
        id: opa
        
      - name: Print Test results
        run: |
          echo "Test Results: ${{ steps.opa.outputs.result }}"

      - name: Create Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: a7160df46e48dff45b24096de9302d38
          filename: csp-security-policies_coverage.json
          label: coverage
#           message: ${{ env.COVERAGE }}
          message: 87
          namedLogo: jest
          color: green
          logoColor: lightblue
