name: Test Policies

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test-rego-policies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull OPA Docker image and run opa test
        uses: docker://openpolicyagent/opa
        with:
          args: "test --ignore=*.yaml --ignore=*.json -v compliance"
  
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull OPA Docker image and run opa test
        uses: docker://openpolicyagent/opa
        with:
          args: "test --ignore=*.yaml --ignore=*.json -v -c compliance > $GITHUB_ENV"
        id: opa_test
      - name: Use the value
        run: echo ${{ steps.opa_test.outputs.digest }}


