name: Test Policies

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test-rego-policies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: OPA test
        uses: docker://openpolicyagent/opa
        with:
          args: "test --ignore=*.yaml --ignore=*.json -v compliance"
      - name: OPA check -strict
        uses: docker://openpolicyagent/opa
        with:
          args: "check --strict --bundle ."

