name: Test Policies

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test-rego-policies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull OPA Docker image and run opa test
        uses: docker://openpolicyagent/opa
        with:
          args: "test --ignore=*.yaml --ignore=*.json -v compliance"
  
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Download OPA Binary
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa
          ./opa -h
      
      - name: Run opa test
        run: |
          ./opa test --ignore=*.yaml --ignore=*.json -v -c compliance
        
#       - name: Use the value
#         run: |
#           echo ${{ steps.opa_test }}
#           echo ${{ steps.opa_test.outputs }}
#           echo ${{ steps.opa_test.outputs.raw }}
#           echo ${{ steps.opa_test.outputs.digest }}
          
#           echo ${{ fromJson(steps.opa_test) }}
#           echo ${{ fromJson(steps.opa_test.outputs) }}


