name: Test Policies

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test-rego-policies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull OPA Docker image and run opa test
        uses: docker://openpolicyagent/opa
        with:
          args: "test --ignore=*.yaml --ignore=*.json -v compliance"
  
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Download OPA Binary
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa
          ./opa -h
      
      - name: Run opa test coverage
        run: |
          echo "::set-output results=/opa test --ignore=*.yaml --ignore=*.json -v -c compliance"
        id: coverage
        
      - name: Echo results
        run: |
          echo ${{ steps.coverage.results }}
          echo ${{ fromJson(steps.coverage.results) }}
        
      - name: Create Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: a7160df46e48dff45b24096de9302d38
          filename: csp-security-policies_coverage.json
          label: coverage
#           message: ${{ env.COVERAGE }}
          message: 87
          namedLogo: Elastic
          color: green
          logoColor: lightblue


