name: Code Coverage Badge

on:
  pull_request:
  push:
    branches: [main]


jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Compliance Directory
        uses: b4b4r07/action-changed-objects@master
        with:
          dirname: 'compliance'
        id: dir

      - name: OPA test
        uses: b4b4r07/action-opa@master
        with:
          coverage: 100%
          files: ${{ steps.dir.outputs.changed }}
        id: opa
        
      - name: Print Test results
        run: |
          echo "Test Results: ${{ steps.opa.outputs.result }}"

      - name: Create Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: a7160df46e48dff45b24096de9302d38
          filename: csp-security-policies_coverage.json
          label: coverage
#           message: ${{ env.COVERAGE }}
          message: 87
          namedLogo: Elastic
          color: green
          logoColor: lightblue
